# This is the .github/workflows/main.yml

name: Deploy on Heroku # Name of the workflow

# Events that trigger a workflow:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  # Check out the following article for more inspiration on setting up a
  test:
    runs-on: ubuntu-latest
    name: 'Run Tests'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: |
          touch .env
          echo SECRET_KEY=secret >> .env
          echo DB_ENTITIES="src/infra/db/typeorm/entities/**.entity{.ts, .js}" >> .env
          echo DB_MIGRATIONS="src/infra/db/typeorm/migrations/**{.ts, .js}" >> .env
          echo DB_ENTITIES_DIR="src/infra/db/typeorm/entities/" >> .env
          echo DB_MIGRATIONS_DIR="src/infra/db/typeorm/migrations/" >> .env
          cat .env
      - run: yarn install
      - run: yarn test

  # Include your test suite here.
  # lint:

  # Lint & format your code over here.
  deploy:
    # If the test & lint jobs don't pass,
    # the deploy job willn't even execute
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploying to Heroku
        # More details available at:
        # https://github.com/akhileshns/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ezwallet-hml"
          heroku_email: "gabriel.fonsecadev@gmail.com"
          healthcheck: "https://ezwallet-hml.herokuapp.com/api/healthcheck"
          rollbackonhealthcheckfailed: true
          delay: 10

